# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: entire cities
email: entirecities@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Entire Cities are a weird country and rock band from Toronto, Ontario, Canada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://entirecities.com" # the base hostname & protocol for your site
twitter_username: entirecities
github_username:  simonborer

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
